#!/usr/bin/env bash
# manager for manage_my_process
case $1 in
	"start")
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo 'manage_my_process started'
		;;
	"restart")
		id=$(cat /var/run/my_process.pid)
		kill -s SIGSTOP $id
		rm /var/run/my_process.pid
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo 'manage_my_process restarted'
		;;
	"stop")
		id=$(cat /var/run/my_process.pid)
		kill -s SIGSTOP $id
		rm /var/run/my_process.pid
		echo 'manage_my_process stopped'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		;;
esac
