#!/usr/bin/env bash
# displays numbers from 1 to 100 FizzBuzz, Fizz, Buzz

for i in {1..100}
do
	if ((i % 15 == 0 ))
	then
	echo "FizzBuzz"
	elif ((i % 3 == 0 ))
	then
	echo "Fizz"
	elif ((i % 5 == 0 ))
	then
	echo "Buzz"
	else echo "$i"
	fi
done
